# Generated by Django 5.0.6 on 2024-06-27 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='records',
            old_name='adress',
            new_name='address',
        ),
    ]
